### PR TITLE
Hanoi

### PR DESCRIPTION
**Pull request by hungle90**
Hanoi DevFest

### CODE REVIEW

**Comment by stefanhoth** [comment]
I think you meant to open this PR against your own fork, not the template.

**Comment by hungle90** [comment]
Hi @stefanhoth,

I want to change the name of URL. But i don't know how to fix it.

**Comment by stefanhoth** [comment]
You need to make the PR against your fork, in your repo and run this. With PR as it is now you are trying to change the main template for everyone.

**Comment by hungle90** [comment]
I 'm sorry for any inconvenience caused

**Comment by ozasadnyy** [comment]
Don't worry  @hungle90 your PR have been rejected, so no changes to original project

**Pull request closed without merging**
