### PR TITLE
Script minification bash scripts are added.

### PR DESCRIPTION
**Pull request by tasomaniac**

### CODE REVIEW

**Comment by ozasadnyy** [comment]
Thanks for contribution!

**Comment by tasomaniac** [comment]
Thank you for the great project. :)

master and develop branches are kinda odd right now. develop and gh-pages are behind master.

**Comment by ozasadnyy** [comment]
I will update all branches with next release.

**Comment by zasadnyy** [comment]
@tasomaniac thanks for contribution. Could you please also update [wiki page](https://github.com/gdg-x/zeppelin/wiki/Resources-optimizations) ?

**Comment by tasomaniac** [comment]
Hey, I've updated the wiki page. And I deleted the page about App Engine. I think it is from past and unrelated. You can revert it if you want. Sorry if it was a mistake :)

So, the wiki page was confusing. There is no `minify_all.bat` and `minify_css.bat`, and corresponding `.sh` files. What happened to those?

**Comment by zasadnyy** [comment]
@ozasadnyy could you please check?

**Comment by ozasadnyy** [comment]
Yep, it's my mistake. I have deleted that bash files but forgot to edit wiki page.

**Comment by tasomaniac** [comment]
But why we don't have scripts for css files?

I am developing our wtm15 web page. And one of my friends make a change in
the main css file. Since it is already one line file I cannot see the
difference.

Should we do the css just like scripts and have minified version separately

**Comment by ozasadnyy** [comment]
There is no need for such script. Because when you developing with Sass it will compile for you .min version of styles. Look here: https://github.com/gdg-x/zeppelin/wiki/Sass-development#running

**Comment by tasomaniac** [comment]
Oh I didn't know that. So we should about Wiki and Readme. 
Also we can add this information there too. Because they are related.

**Pull request merged**
