### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alouanemed**
add MENAT GDG Summit 2014 to the list

### CODE REVIEW

**Comment by zasadnyy** [comment]
Closing pull request. Added MENAT Summit 2014 manually

**Comment by alouanemed** [comment]
LOL ,  why you didn't just merge?

**Comment by zasadnyy** [comment]
Auto merge didn't worked coz you've forked repository long time ago and
there were a lot of changes. For me it was easier to copy changes than
cloning both branches, merge locally and push back.

**Comment by alouanemed** [comment]
aaah you are talking about merge conflict.
It's okay :)

**Pull request closed without merging**
